### ISSUE TITLE
[1.0.2] Feathers crashes the game on resource reload

### ISSUE THREAD

**Issue by FyreAlchemage** [ElenaiDev/Feathers#11]
It seems like Feathers is trying to send network packets when it shouldn't be able to, resulting in a crash, this happens when reloading resources, particularly tested via switching resource packs.

[crash-2022-12-25_17.47.09-client.txt](https://github.com/ElenaiDev/Feathers/files/10300719/crash-2022-12-25_17.47.09-client.txt)

**Comment by FyreAlchemage** [comment]
Looking at issue reports for Elenai Dodge, the general consensus seems to be that installing PlayerAnimator would fix this. It did not in this case.

**Comment by ElenaiDev** [comment]
Thanks for spotting this! I'll get working on a fix 👍
As a side note, feathers does not use Player Animator, that was an issue with Elenai Dodge 2 that is now (hopefully!) resolved).

Thanks for the crash log too :)

**Comment by V972** [comment]
Same issue here
[crash-2023-01-07_18.46.23-client.txt](https://github.com/ElenaiDev/Feathers/files/10366750/crash-2023-01-07_18.46.23-client.txt)

**Comment by FanRenLa** [comment]
1.19.2-1.0.3
[crash-2023-02-07_21.09.50-client.txt](https://github.com/ElenaiDev/Feathers/files/10675322/crash-2023-02-07_21.09.50-client.txt)

**Comment by KarinMiku** [comment]
still happening on 1.18.2 😕

**Comment by ElenaiDev** [comment]
Sorry for taking so long to get to this! I'm looking into this at the moment, but so far I'm unable to reproduce the bug, out of interest for anyone who can help, does it crash for you both when inside a world and on the main menu?

Thank you!

**Comment by ygoroffici** [comment]
Unsure if you have figured it out already, but it only happens on the main menu! Changing resource packs inside a world has no problems.
