### ISSUE TITLE
I have a foolish idea

### ISSUE THREAD

**Issue by wanji404** [ElenaiDev/Feathers#15]
Excuse me, can you add a curse enchantment to increase the weight of the armors？Personally, I believe it can increase the randomness and entertainment of the game. Thank you if you are planning to include it in the update plan

**Comment by Roman-Pretty** [comment]
This is not a foolish idea, it's great!
Working on it for the new update :)

**Comment by ElenaiDev** [comment]
This is not a foolish idea, it's great!

I have just implemented it for the next update.
