### ISSUE TITLE
Log Spam with Unable to Calculate Weight of Non-Armor Item

### ISSUE THREAD

**Issue by BT-47** [ElenaiDev/Feathers#20]
Whenever a non-armor item is worn like the Engineer's Goggles from Create it spams the logs with 

`[Server thread/WARN] [feathers/]: Attempted to calculate weight of non armor item: item.create.goggles`

There is no way to stop this behavior and even when a manual override of 0 or 1 is set for the item it still spams the logs.

**Comment by ElenaiDev** [comment]
Thank you for pointing this out! I am fixing this now, sorry for the inconvenience :)

**Comment by BT-47** [comment]
Thanks! Would this end up going to 1.19.4/1.20 or 1.19.2? (My modpack is stuck in 1.19.2 so it would be nice if it updated that version too)

Thank you for making such a good mod, I was worried it would be abandoned in the 1.16 era, glad to see it's back. Best dodge mod in Minecraft in my opinion, keep up the good work for the modded community :)

**Comment by ElenaiDev** [comment]
That's so kind of you to say! 
I will be releasing it on all versions including 1.19.2 very soon (don't worry!), sorry for the wait; I'm compiling together a collection of patches for other mods, this fix will be uploaded soon.

Thank you very much :)

**Comment by snowinmars** [comment]
Still on 1.20.1 + forge 47.1.47 + feathers 1.1

![image](https://github.com/ElenaiDev/Feathers/assets/5859735/fdf3335b-e7c7-42a7-8552-73081aa95572)

Can you reopen the issue, please?

**Comment by bruglet** [comment]
@ElenaiDev It's been a while, but I wanted to let you know that your commit [8d954e6](https://github.com/ElenaiDev/Feathers/commit/8d954e6af1e0ae570a2f948919a9219f21bd9026) never made it through to any branch and thus this issue was never fixed! I'll submit a pull request right now to implement the change :)

**Comment by Aceplante** [comment]
Still occurring in 1.20.1
