### ISSUE TITLE
Mild incompatibility with Classic Bars Forge 1.19.2

### ISSUE THREAD

**Issue by Churchexe** [ElenaiDev/Feathers#21]
This mod has an aesthetic incompatibility with the [Classic Bars ](https://www.curseforge.com/minecraft/mc-mods/classic-bars)HUD mod. 
Reproduced on a new instance with up-to-date forge using only
classicbar-1.19.2-6.1.2
feathers-1.1.1

Whereas the feathers should be a bar like the other UI elements, they are instead shown as normal minecraft icons. (for what it's worth, classic bars has had quite seamless integration with other things in the past, so hopefully this is a relatively easy fix that won't require redoing too much)

**Comment by ElenaiDev** [comment]
Thank you for spotting this! I'm fixing this at the moment :)

**Comment by TheEffortFighter** [comment]
This issue also occurs in 1.18.2, could you possibly fix it?
