### ISSUE TITLE
1.12.2 Backport please!

### ISSUE THREAD

**Issue by Ski-z** [ElenaiDev/Feathers#3]
Hey Elenai, I absolutely love your mods. But 1.12.2 is actually experiencing a huge resurgence; would you consider a backport?

Thank you!

**Comment by ElenaiDev** [comment]
Hi!
Feathers is included in the 1.12.2 version of Elenai Dodge 2 found [here](https://www.curseforge.com/minecraft/mc-mods/elenai-dodge-2/files/3343308).

Thank you for the kind words!
