### ISSUE TITLE
Missing Lightweight Enchantment

### ISSUE THREAD

**Issue by ZilverLazarus** [ElenaiDev/Feathers#4]
I'm not sure if it's intentional, but I can't find the Lightweight enchantment in the JEI menu or an option in the config files that enables it. If it's not intentional, please add it back or give an option that enables it.

Edit: Also wasn't sure if I should put this on Elenai Dodge's page or this one

**Comment by ElenaiDev** [comment]
I temporarily removed it as I felt it was a little overpowered at the time, however I'll add it back as an option in the very near future. You were right to put it on this page, thanks for addressing the issue!

**Comment by ZilverLazarus** [comment]
> I temporarily removed it as I felt it was a little overpowered at the time, however I'll add it back as an option in the very near future. You were right to put it on this page, thanks for addressing the issue!

And thank you for the reply. Glad to hear that it's coming back. ^^
