### ISSUE TITLE
Feathers Bar overlaps with other mods that add bars

### ISSUE THREAD

**Issue by decovulous** [ElenaiDev/Feathers#6]
I've been setting up a modpack and found the Feathers overlapping with some bars from other mods.

Here it overlaps with a bar from Origins.
![image](https://user-images.githubusercontent.com/120059142/206300178-5c13bb0a-ed1a-4971-808b-0541f8213d04.png)

and here it overlaps with the Origins bar and the Mana bar from Spells & Shields.
![image](https://user-images.githubusercontent.com/120059142/206300359-95b1dca2-361a-42b6-b6bf-4cc17c51f7f2.png)

I was able to move the Mana bar above the health using its config file, which fixed that problem. But Origins doesn't provide that kind of customization. Hope there's a solution because I really love this mod! Thank you!

**Comment by zacharyboland** [comment]
Same here on 1.19.2 forge
![image](https://user-images.githubusercontent.com/63996164/206358028-b87e2634-55a9-4c05-a441-a30481324b20.png)

**Comment by ElenaiDev** [comment]
Hi! Thank you for your kind words :) It's possible to move the feathers bar in the client config for feathers, just change the y position value by ten.

Any issues, let me know. (I'll leave this open just incase)

Have a lovely day!

**Comment by zacharyboland** [comment]
That is an option, but making it dynamic would make it so that if you have a horse of health of one line, it would go right above it, and a horse with more health, it will dynamically go above the two lines horses health.
Does that make sense?

**Comment by zacharyboland** [comment]
Also, it seems to move on its own when going underwater because of the bubbles, so it just moves around even if i have it placed somewhere else on the screen, which is quite annoying to have happening :/

**Comment by ElenaiDev** [comment]
Thanks for bringing this up! I’ll Patch it soon :)

**Comment by Pretender8** [comment]
![image](https://user-images.githubusercontent.com/34997550/212524155-a6206c19-a608-4706-8f76-4c4a7369f58d.png)
A similar overlap happens with the Redstone Arsenal mod. It is possible to move it up using the config setting, but apparently it can be done with another method according to one of the devs?
> they need to add  - gui.rightHeight and then increment gui.rightHeight by however tall their overlay is

**Comment by ElenaiDev** [comment]
For whatever reason, I though that gui.rightHeight had been removed. Very glad I was wrong, thank you for this!
