### ISSUE TITLE
Feathers overlap with horse healthbars

### ISSUE THREAD

**Issue by DeshiDesu** [ElenaiDev/Feathers#7]
![Screenshot from 2022-12-16 20-56-17](https://user-images.githubusercontent.com/120287925/208218499-139a28e8-d9b4-4cdf-9b11-ae1d9db37f8c.png)
This is not an issue with mods overlapping each other. I think feathers just doesn't automatically adjust its position accordingly when riding a horse or any other mounts.

**Comment by ElenaiDev** [comment]
Thanks for the explanation! I’ll patch this soon :)

**Comment by DeshiDesu** [comment]
I should be the one thanking you. Your mod helped me create the right modpack for me. I appreciate your hard work and please continue to be amazing.
