### ISSUE TITLE
[Suggestion] Make Adjusting Feathers Toggleable

### ISSUE THREAD

**Issue by DeshiDesu** [ElenaiDev/Feathers#9]
In reference to this issue [here](https://github.com/ElenaiDev/Feathers/issues/7).

![image](https://user-images.githubusercontent.com/120287925/209449105-c32416d6-641f-462d-a9fd-be8fbf7cdd82.png)

When you do patch this issue, could you make this feature toggleable (on/off)? My reasoning for this is that I have way too many bars, namely Origins, Tough as Nails, and Feathers. To organize these bars I have organized it in such a way that does feel visually balanced (one side has too many bars than the other). So I moved feathers to the left side of the hotbar. The issue with this is now when you do make feathers adjustable according to mount health bars, you now have a moving feathers when it doesn't have to. In any case this is just a rant of mine, you can ignore this if you want to, or I should just add another mod that adds bars on the left instead.

**Comment by ElenaiDev** [comment]
This is a good suggestion, thank you! I've included a toggle in the fix I'm making :)
